<?php
/*
  Copyright (C) 2015-2018 www.allo.com - All Rights Reserved.
  FreeBlox is the Freeware GUI Management Tool for Blox [http://www.blox.org]
  You are granted a non-exclusive License to use the FreeBlox software for
  any purposes for an unlimited period of time. The software product under
  this License is provided free of charge.
  Even though a license fee is not paid for the use of Freeware Version
  software, it does not mean that there are no conditions for using such
  software:

   1. The Software may be installed and used by the Licensee for any legal
      purpose.

   2. The Software may be installed and used by the Licensee on any number
      of systems.

   3. The Software can be copied and distributed under the condition that
      original copyright notice and disclaimer of warranty will stay intact,
      and the Licensee will not charge money or fees for the Software
      product, except to cover distribution costs.

   4. The Licensee will not have any proprietary rights in and to the
      Software. The Licensee acknowledges and agrees that the Licensor retains
      all copyrights and other proprietary rights in and to the Software.

   5. Use within the scope of this License is free of charge and no royalty
      or licensing fees shall be paid by the Licensee.
*/
    class UtmReportsCmd
    {
        const EXIT_CMD = -1;
        const GET_CPU_STAT = 0;
        const GET_MEM_STAT = 1;
        const GET_CONNS_STAT = 2;
        const GET_WAN_USAGE_STAT = 3;
        const GET_FW_STAT = 4;
        const GET_IPS_STAT = 5;
        const GET_SYS_CPU_MODEL = 6;
        const GET_SYS_MEM_INFO = 7;
        const GET_SYS_LAN_IF_ADDR = 8;
        const GET_IF_ADDR = 9;
        const GET_TIME_ZONE = 10;
        const GET_IF_LIST = 11;
        const GET_IF_STATUS = 12;
    }
?>
